const types = {
  ADD_TASK: "ADD_TASK",
  DELETE_TASK: "DELETE_TASK",
  EDIT_TASK: "EDIT_TASK",
  DONE_TASK: "DONE_TASK",
  SELECTED_TASK: "SELECTED_TASK",
  SHOW_ADD_OR_EDIT_TASK_MODAL: "SHOW_ADD_OR_EDIT_TASK_MODAL",
  SHOW_TASK_DETAILS_MODAL: "SHOW_TASK_DETAILS_MODAL",
  SHOW_DONE_TASKS_MODAL: "SHOW_DONE_TASKS_MODAL",
};

export default types;
